config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users

  resources :products

  get 'pages/about'

  get 'pages/contact'

  get 'pages/services'

  get 'pages/shop'

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

    acts_as_sellable
    if Rails.env.development?
    has_attached_file   :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "images.jpg"
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
 else
      has_attached_file :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "images.jpg",
                        :storage => :dropbox,
                        :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                        :path => ":style/:id_:filename"
    end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_orderer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def services
  end

  def shop
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def acts_as_sellable
      attr_accessible :piggybak_sellable_attributes
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new()
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :admin_login, :logout)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse">
 <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-footer">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Webconcierge</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
        <li><a href="/pages/services">Services</a></li>
        <li><a href="/pages/shop">Shop</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Basket</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-inverse">
 <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Webconcierge</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %>></li>
        <li><%= link_to "Services", pages_services_path %></li>
        <li><%= link_to"Shop", pages_shop_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Sign Out",  destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Edit Profile",  edit_user_registration_path %></li>
        <% else %>
        <li><%= link_to "Sign Up",  new_user_registration_path %></li>
        <li><%= link_to "Log In",  new_user_session_path %></li>
        <% end %>

        <li><a href="#">Basket</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webconcierge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/header' %>

<div class="container">
        
        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
              
            <% end %>
          <% end %>  
        
  
  <%= yield %>




<%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/services.html.erb
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>

app/views/pages/shop.html.erb
<h1>Pages#shop</h1>
<p>Find me in app/views/pages/shop.html.erb</p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product, class: "btn btn-link" %> |
<%= link_to 'Back', products_path, class: "btn btn-link" %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<div class="centre">
  <div class="row">
      <% @products.each do |product| %>
        <div class="col-md-4">
          <div class="thumbnail">
            <%= image_tag product.image.url %>
              <div class="caption">
              <h3><%= product.name %><h3>
                <p><%= number_to_currency(product.price, unit: "€",) %></p>
                <%= link_to 'Show', product, class: "btn btn-link" %>
              </div>
          </div>
        </div>
        <% end %>
</div>
</div>
<br>

<%= link_to 'New Product', new_product_path, class: "btn btn-link" %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path, class: "btn btn-link"  %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col-md-6">
      <div class ="thumbnail">
        <%= image_tag @product.image.url(:medium) %>
        </div>
     </div>
    <div class="col-md-6">
      <h3><%= @product.name %></h3>
      <p>  <%= @product.description %></p>
      <p>  <%= number_to_currency(@product.price) %></p>
  </div>
  </div>
  

<%= link_to 'Back', products_path, class: "btn btn-link" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :admin_login %><br>
    <%= f.text_field :admin_login %>
  </div>
  <div class="field">
    <%= f.label :logout %><br>
    <%= f.text_field :logout %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Admin login</th>
      <th>Logout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.admin_login %></td>
        <td><%= user.logout %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Admin login:</strong>
  <%= @user.admin_login %>
</p>

<p>
  <strong>Logout:</strong>
  <%= @user.logout %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>